///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "61C9707B-7F2B-4912-A0B1-AA940C779DBC"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (BON2Component2)"
#define COCLASS_UUID "503F991C-A1CF-486E-8F9D-0CC0AD23252D"
#define COCLASS_NAME "MGA Interpreter CoClass (BON2Component2)"
#define COCLASS_PROGID "MGA.Interpreter.BON2Component2"

#define COCLASS_UUID_EXPLODED1  0x503f991c
#define COCLASS_UUID_EXPLODED2   0xa1cf
#define COCLASS_UUID_EXPLODED3   0x486e
#define COCLASS_UUID_EXPLODED4   0x8f
#define COCLASS_UUID_EXPLODED5   0x9d
#define COCLASS_UUID_EXPLODED6   0xc
#define COCLASS_UUID_EXPLODED7   0xc0
#define COCLASS_UUID_EXPLODED8   0xad
#define COCLASS_UUID_EXPLODED9   0x23
#define COCLASS_UUID_EXPLODED10  0x25
#define COCLASS_UUID_EXPLODED11  0x2d


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME _T("BON2Component2")


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT _T("BON2Component2 Interpreter")

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS _T("DataFlowModel")


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
